# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # By Default the name is "vagrant_default_<timestamp>" where the timestamp is the creation current UNIX timestamp.
  config.vm.provider "virtualbox" do |v|
      v.name = "Awesome LAMP Stack by HunCyrus"
  end

  # Be sure you have the correct power in your machine
  config.vm.provider "virtualbox" do |v|
    # v.memory = 512 # default
    v.memory = 1024
    # v.cpus = 1 # default
    v.cpus = 1
  end

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  # Create a private network, which allows host-only access to the machine using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.22"

  # Share an additional folder to the guest VM. The first argument is the path on the host to the actual folder.
  # The second argument is the path on the guest to mount the folder.
  config.vm.synced_folder "./../myProject/", "/var/www/html"

  # Define the bootstrap file: A (shell) script that runs after first setup of your box (= provisioning)
  config.vm.provision :shell, path: "bootstrap.sh"
end
